### ISSUE TITLE
MetricServer takes an IEnumerable<IOnDemandCollector> parameter, but does not use it

### ISSUE THREAD

**Issue by godefroi** [andrasm/prometheus-net#66]
The `MetricServer` constructor passes the parameter to the `MetricHandler` constructor, but `MetricHandler` does not use the parameter either.

This lead to some confusion on how to implement `IOnDemandCollector` type setups, at least in my case.

**Comment by sandersaares** [comment]
Good point. This parameter is only used if the default registry is used and the usage pattern in that case is a bit suspect, as well. In general, metrics should be exported from a registry and you can register on-demand metrics with a registry but passing both a registry and on-demand metrics to a metric server is a confusing pattern.

The intended use case seems to be to allow the default set of on-demand collectors (which is various .NET metrics by default) to be overridden.

I will see if I can somehow adjust this pattern to remove the element of confusion while retaining the ability to customize the default set of on demand collectors.

**Comment by sandersaares** [comment]
The selected implementation change is the following:

* The singleton `DefaultCollectorRegistry.Instance` will always have the built-in set of default collectors registered.
* To avoid registering the builtin collectors, one can simply use a custom instance of `DefaultCollectorRegistry` instead of the singleton (or another implementation of `ICollectorRegistry`.
* Calls to `IOnDemandCollector.RegisterMetrics()` lose the context of which collector registry is being worked with. Some existing implementations assume it is always the singleton registry, which is not always a valid assumption. A registry parameter will be added to this method.

Does this resolve the confusion you mention? It may be that there are more confusing aspects to this, so please let me know if something remains developer-unfriendly in the API.

**Comment by sandersaares** [comment]
The above change has been implemented in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
